In [1]:

Arows = int(input("введите число строк: "))  
print("введите матрицу:")
A = [list(map(float, (input(f"строка {i+1}: ").split()))) for i in range(Arows)]
B = map(float, input("Введите столбец свободных членов: ").split())
B = list(B)
import time 
start = time.time()
def Conclusion(Ax, Bx, introduced):
    for row in range(len(Bx)):
        print("(")
        for kol in range(len(Ax[row])):
             print("\t{1:1.3f}{0}".format("" if (introduced is None or introduced != (row, kol)) else"", Ax[row][kol]), end='')
        print("\t) * (\tX{0}) = (\t{1:1.3f})".format(row + 1, Bx[row]))
def ChangeRows(Ax, Bx, row1, row2):
    Ax[row1], Ax[row2] = Ax[row2], Ax[row1]
    Bx[row1], Bx[row2] = Bx[row2], Bx[row1]
def DivideRow(Ax, Bx, row, delt):
    Ax[row] = [a / delt for a in Ax[row]]
    Bx[row] /= delt
def AdditionRows(Ax, Bx, row, source_row, number):
    Ax[row] = [(a + k * number) for a, k in zip(Ax[row], Ax[source_row])]
    Bx[row] += Bx[source_row] * number
def Gauss(Ax, Bx):
    column = 0
    while (column < len(Bx)):
        print("Максимальный по модулю элемент в {0}-м столбце:".format(column + 1))
        current_row = None
        for r in range(column, len(Ax)):
            if current_row is None or abs(Ax[r][column]) > abs(Ax[current_row][column]):
                 current_row = r
        if current_row is None:
            print("решений нет")
            return None
        Conclusion(Ax, Bx, (current_row, column))
        if current_row != column:
            print("Переставляем строку с найденным элементом:")
            ChangeRows(Ax, Bx, current_row, column)
            Conclusion(Ax, Bx, (column, column))
        print("Приводим строку с найденным элементом:")
        DivideRow(A, B, column, A[column][column])
        Conclusion(Ax, Bx, (column, column))
        print("Обрабатываем нижележащие строки:")
        for r in range(column + 1, len(Ax)):
            AdditionRows(Ax, Bx, r, column, -Ax[r][column])
        Conclusion(Ax, Bx, (column, column))
        column += 1
    X = [0 for b in Bx]
    for i in range(len(Bx) - 1, -1, -1):
        X[i] = Bx[i] - sum(x * a for x, a in zip(X[(i + 1):], Ax[i][(i + 1):]))
    print("Ответ:")
    print("\n".join("X{0} =\t{1:1.3f}".format(i + 1, x) for i, x in enumerate(X)))
    return X
print("Исходная СЛАУ:")
Conclusion(A, B, None)
print("Решение:")
Gauss(A, B)
end = time.time() - start
print(end)

введите число строк: 3
введите матрицу:
строка 1: 1 2 3 
строка 2: 3 2 5
строка 3: 7 6 4 
Введите столбец свободных членов: 1 1 1
Исходная СЛАУ:
(
	1.000	2.000	3.000	) * (	X1) = (	1.000)
(
	3.000	2.000	5.000	) * (	X2) = (	1.000)
(
	7.000	6.000	4.000	) * (	X3) = (	1.000)
Решение:
Максимальный по модулю элемент в 1-м столбце:
(
	1.000	2.000	3.000	) * (	X1) = (	1.000)
(
	3.000	2.000	5.000	) * (	X2) = (	1.000)
(
	7.000	6.000	4.000	) * (	X3) = (	1.000)
Переставляем строку с найденным элементом:
(
	7.000	6.000	4.000	) * (	X1) = (	1.000)
(
	3.000	2.000	5.000	) * (	X2) = (	1.000)
(
	1.000	2.000	3.000	) * (	X3) = (	1.000)
Приводим строку с найденным элементом:
(
	1.000	0.857	0.571	) * (	X1) = (	0.143)
(
	3.000	2.000	5.000	) * (	X2) = (	1.000)
(
	1.000	2.000	3.000	) * (	X3) = (	1.000)
Обрабатываем нижележащие строки:
(
	1.000	0.857	0.571	) * (	X1) = (	0.143)
(
	0.000	-0.571	3.286	) * (	X2) = (	0.571)
(
	0.000	1.143	2.429	) * (	X3) = (	0.857)
Максимальный по модулю элемент в 2-м столбце:
(
	1.000

In [2]:
import numpy as np
Arows = int(input("введите число строк: "))  
print("введите матрицу:")
A = [list(map(float, (input(f"строка {i+1}: ").split()))) for i in range(Arows)]
B = map(float, input("Введите столбец свободных членов: ").split())
B = list(B)
import time 
start = time.time()
C = np.linalg.solve(A, B)
print(C)
end = time.time() - start
print(end)

введите число строк: 3
введите матрицу:
строка 1: 1 2 3
строка 2: 3 2 5
строка 3: 7 6 4
Введите столбец свободных членов: 1 1 1
[-0.22222222  0.27777778  0.22222222]
0.002864837646484375


In [3]:
import numpy as np

n = 3
print("введите матрицу:")
A = [list(map(float, (input(f"строка {i+1}: ").split()))) for i in range(n)]
B = map(float, input("Введите столбец свободных членов: ").split())
B = list(B)
import time 
start = time.time()
L = np.zeros((3,3))
L[0][0]=(A[0][0])**(1/2)
L[1][0]=A[1][0]/L[0][0]
L[2][0]=A[2][0]/L[0][0]
L[1][1]=(A[1][1]-L[1][0]**2)**(1/2)
L[2][1]=(A[2][1]-L[1][0]*L[2][0])/L[1][1]
L[2][2]=(A[2][2]-L[2][0]**2-L[2][1]**2)**(1/2)

Ly=np.linalg.inv(L)
Y=np.matmul(Ly, B) 
Lt=L.transpose()
Lx=np.linalg.inv(Lt)
X=np.matmul(Lx, Y)

print (X)
end = time.time() - start
print(end)

введите матрицу:
строка 1: 81 -45 45
строка 2: -45 50 -15
строка 3: 45 -15 38
Введите столбец свободных членов: 531 -460 193
[ 6. -5. -4.]
0.005531787872314453


In [7]:
import numpy as np
from time import time
from scipy.linalg import solve_triangular
Arows = int(input("введите число строк: "))  
print("введите матрицу:")
A = [list(map(float, (input(f"строка {i+1}: ").split()))) for i in range(Arows)]
B = map(float, input("Введите столбец свободных членов: ").split())
B = list(B)
import time
start = time.time()
#Разложение Холецкого
for i in range(10000):
    L = np.linalg.cholesky(A)
    Y = solve_triangular(L, B, lower = True, check_finite = False)
    X = solve_triangular(L, Y, lower = True, trans = 1, check_finite = False)
print(X)
end = time.time() - start
print(end)

введите число строк: 3
введите матрицу:
строка 1: 81 -45 45
строка 2: -45 50 -15
строка 3: 45 -15 38
Введите столбец свободных членов: 531 -460 193
[ 6. -5. -4.]
0.2476811408996582
